version: "3"

volumes:
  data:
    driver: local

services:
  web:
    container_name: web
    build:
      context: docker/nginx
      args:
        - PHP_UPSTREAMS=php-fpm-80 php-fpm-74
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:/srv/www
      - ./sites:/etc/nginx/sites-available

  php-fpm-80:
    container_name: php-fpm-80
    build:
      context: docker/php-fpm
      args:
        - PHP_VERSION=8.0
    volumes:
      - ${APP_CODE_PATH_HOST}:/srv/www

  php-fpm-74:
    container_name: php-fpm-74
    build:
      context: docker/php-fpm
      args:
        - PHP_VERSION=7.4
    volumes:
      - ${APP_CODE_PATH_HOST}:/srv/www

  php-cli-80:
    container_name: php-cli-80
    build:
      context: docker/php-cli
      args:
        - PHP_VERSION=8.0
    volumes:
      - ${APP_CODE_PATH_HOST}:/srv/www
      - ./supervisor:/etc/supervisord.d

  php-cli-74:
    container_name: php-cli-74
    build:
      context: docker/php-cli
      args:
        - PHP_VERSION=7.4
    volumes:
      - ${APP_CODE_PATH_HOST}:/srv/www
      - ./supervisor:/etc/supervisord.d

  mysql-80:
    container_name: mysql-80
    build:
      context: docker/mysql
      args:
        - MYSQL_VERSION=8
    ports:
      - "3306:3306"
    volumes:
      - ~/.docker-php-dev/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  postgres-131:
    container_name: postgres-13
    build:
      context: docker/postgres
      args:
        - POSTGRES_VERSION=13.1
    ports:
      - "5432:5432"
    volumes:
      - ~/.docker-php-dev/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root

  mongo-4:
    container_name: mongo-4
    build:
      context: docker/mongo
      args:
        - MONGO_VERSION=4
    ports:
      - "27017:27017"
    volumes:
      - ~/.docker-php-dev/data/mongo:/data/db

  memcache:
    container_name: memcache
    build:
      context: docker/memcached
    ports:
      - "11211:11211"

  redis:
    container_name: redis
    build:
      context: docker/redis
    ports:
      - "6379:6379"
    volumes:
      - ~/.docker-php-dev/data/redis:/data

  elasticsearch-7:
    container_name: elasticsearch-7
    build:
      context: docker/elasticsearch
      args:
        - ElASTICSEARCH_VERSION=7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ~/.docker-php-dev/data/elasticsearch:/usr/share/elasticsearch/data

  mail:
    container_name: mail
    build:
      context: docker/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
